### PR TITLE
Fix Mac compilation doco

### PR DESCRIPTION
**Pull request by xenomorpheus**
Fix paths, spelling and grammar.

### CODE REVIEW

**Comment by defnax** [comment]
> Fix paths, spelling and grammar.

hi, you was able to compile retroshare on macos?
i had issues to link openssl

here is the other mac os instruction:
https://github.com/RetroShare/RetroShare/blob/master/build_scripts/OSX/MacOS_X_InstallGuide.md

**Comment by defnax** [comment]
here is new docs page:
https://github.com/RetroShare/docs
https://retrosharedocs.readthedocs.io/en/latest/

**Comment by xenomorpheus** [comment]
> here is new docs page:
> https://github.com/RetroShare/docs
> https://retrosharedocs.readthedocs.io/en/latest/

Hi @defnax 

Retroshare is project I would like to be involved with.  

I am very concerned that there is a very large amount of misleading documentation. 

How do we remove the duplicates and achieve "One Source of Truth" ?

So you mentioned that the following is the new docs page.
https://github.com/RetroShare/docs

Why does https://github.com/RetroShare/documentation exist ?  Would it be best to remove "documentation" so to avoid confusion ?

You mentioned "here is the other mac os instruction:"
https://github.com/RetroShare/RetroShare/blob/master/build_scripts/OSX/MacOS_X_InstallGuide.md
Again this is very concerning.  Why does the above install guide contain "Compilation on MacOS" ?
Should the "MacOS_X_InstallGuide.md" be edited ? 
Replace the compilation steps with a link to the downloads page ?

Some of the documents in that folder are 5-10 years old and unlikely to be relevant.


https://sourceforge.net/projects/retroshare/
Why does this website contain a link to http://retroshare.net  ?
Why does sourceforge.net website have downloads that are so old? 
Would it be best to replace all content on sourceforge.net with just a redirect to https://retroshare.cc  ?

I see you are asking for Mac developers. I may continue this there.  https://github.com/RetroShare/RetroShare/issues/2389

**Comment by defnax** [comment]
i merged but it will never get synced

**Comment by xenomorpheus** [comment]
Can you please explain where it won't get synced to ?

Thank you for the warning, and for merging the PR.

**Comment by defnax** [comment]
i said this repo dont get snyced more since 2019
https://github.com/RetroShare/documentation/issues/77#issuecomment-629690861

the Admin has the rights to fix this he left retroshare.
maybe the webhook needs to new configured on Github repo + Edit on the readthedocs account too.
1. Repo Admin gone (Cave)
2. https://retroshare.readthedocs.io ( Cave is admin there too )

Here you can read about webhooks and Github, 
https://docs.readthedocs.io/en/stable/webhooks.html

**Pull request merged**
